name: Continuous Delivery of Python package

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - ".github/**"
  workflow_dispatch:
    inputs:
      production_release:
        description: "Production release?"
        type: boolean
        required: true
        default: true
      bump_manual_version:
        description: "Manually bump version number"
        type: boolean
        required: false
        default: false
      manual_version:
        description: "Version number to set (e.g. 1.2.3)"
        type: string
        required: false

concurrency: release

permissions:
  contents: write
  packages: read

jobs:
  ci-check-python:
    name: Check Python
    uses: ./.github/workflows/check-python.yaml

  ci-build-python:
    name: Build Python
    uses: ./.github/workflows/build-python.yaml
    needs: ci-check-python

  release:
    name: Release Library
    needs: ci-build-python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch entire repository history so we can determine version number from it
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Get branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: get_branch

      - name: Set Git user as GitHub actions
        run: git config --global user.email "actions@github.com" && git config --global user.name "github-actions"

      - name: Create Continuous Deployment - Beta (non-prod)
        if: steps.get_branch.outputs.branch == 'main' && !inputs.production_release
        run: |
          poetry run semantic-release \
            -v DEBUG \
            --prerelease \
            --define=branch=main \
            --define=upload_to_repository=true \
            publish
          gh release edit --prerelease "v$(poetry run semantic-release print-version --current)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_API_KEY }}

      - name: Create Continuous Deployment - Production
        if: steps.get_branch.outputs.branch == 'main' && inputs.production_release
        run: |
          poetry run semantic-release \
            -v DEBUG \
            --define=version_source="commit" \
            --define=patch_without_tag=true \
            --define=upload_to_repository=true \
            --define=branch=main \
            publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_API_KEY }}

      - name: Create Continuous Deployment - Manual Version
        if: inputs.bump_manual_version && !inputs.production_release
        run: |
          # Validate manual version is provided
          if [ -z "${{ inputs.manual_version }}" ]; then
            echo "Error: manual_version is required when release_type is 'manual'"
            exit 1
          fi

          # Set the manual version from input
          VERSION=${{ inputs.manual_version }}

          # Update version in pyproject.toml
          poetry version $VERSION

          # Update CHANGELOG.md
          TODAY=$(date +%Y-%m-%d)
          NEW_ENTRY="## v$VERSION ($TODAY)\n\n### Chore\n\n* Bumped major version"
          sed -i 's/<!--next-version-placeholder-->/<!--next-version-placeholder-->\n\n'"$NEW_ENTRY"'/' CHANGELOG.md

          # Commit both changes together
          git add pyproject.toml CHANGELOG.md
          git commit -t "$VERSION" -m "$VERSION"

          # Create and push tag
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"
          git push origin main

          # Build the package
          poetry build

          # Create GitHub release
          gh release create "v$VERSION" --title "v$VERSION" ./dist/* --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
